language: cpp
compiler:
  - gcc
  - clang
env:
  - LIBCXX=true BUILD_TYPE=Debug
  - LIBCXX=true BUILD_TYPE=Release
  - LIBCXX=false BUILD_TYPE=Debug
  - LIBCXX=false BUILD_TYPE=Release
  global:
    - GCC_VERSION="4.9"
matrix:
  exclude:
    - compiler: gcc
      env: LIBCXX=true BUILD_TYPE=Debug
    - compiler: gcc
      env: LIBCXX=true BUILD_TYPE=Release

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-${GCC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which g++-${GCC_VERSION}) /usr/bin/g++ ; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which gcc-${GCC_VERSION}) /usr/bin/gcc ; fi

  - if [ "$LIBCXX" == "true" ]; then cwd=$(pwd); fi
  - if [ "$LIBCXX" == "true" ]; then export CXXFLAGS="-std=c++0x -stdlib=libc++"; fi
  - if [ "$LIBCXX" == "true" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
  - if [ "$LIBCXX" == "true" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$LIBCXX" == "true" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$LIBCXX" == "true" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$LIBCXX" == "true" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$LIBCXX" == "true" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$LIBCXX" == "true" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi
  - if [ "$LIBCXX" == "true" ]; then CXX_FLAGS="${CXX_FLAGS} -stdlib=libc++ -I/usr/include/c++/v1/"; fi
  - if [ "$LIBCXX" == "true" ]; then CXX_LINKER_FLAGS="${CXX_FLAGS} -L/usr/lib/ -lc++"; fi

install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
  - bii --version
  - $CXX --version
  - bii init
script:
  - bii find
  - bii cpp:configure -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $CXX) -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_EXE_LINKER_FLAGS="${CXX_LINKER_FLAGS}"
  - bii cpp:build
  - ./bin/manu343726_snail_test
after_success:
- cp README.md blocks/manu343726/snail #Update readme
deploy:
  provider: biicode
  user: manu343726
  password:
    secure: D+KebyVKL+LGd05Wpz/WOdQZAKc7RyTY7H+DGpO54TlD8N5WrhV2HKmqrFjMKEB8GZ4WNoDGRVH/WcwhgTipjf+o/UVgk43glSq3C3D+hoETCoorqLuXvYp7Fiv3q4QICDE/3TXHPlnEiUBTYJFH+OwEQnZO0gnr1tKGcZFmEv0=
  skip_cleanup: true #Update block readme
